# Generated by Django 4.2.14 on 2024-10-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_authcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenLogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokenType', models.CharField(max_length=50, null=True)),
                ('tokenValue', models.CharField(max_length=5000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
