# Generated by Django 4.2.14 on 2024-10-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyersapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenOrderTempData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=200)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('premium_price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('average_price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('sl_price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('exp_loss', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('quantity', models.IntegerField(null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_averaged', models.IntegerField(null=True)),
            ],
        ),
    ]
