# Generated by Django 4.2.14 on 2024-10-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyersapi', '0002_openordertempdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingconfigurations',
            name='is_averaged',
            field=models.BooleanField(default=False),
        ),
    ]
