# Generated by Django 4.2.14 on 2024-10-06 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyersapi', '0003_tradingconfigurations_is_averaged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingconfigurations',
            name='is_averaged',
        ),
    ]
