# Generated by Django 4.2.14 on 2024-10-06 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyersapi', '0004_remove_tradingconfigurations_is_averaged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openordertempdata',
            old_name='is_averaged',
            new_name='averaging_count',
        ),
    ]
