# Generated by Django 4.2.14 on 2024-10-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyersapi', '0005_rename_is_averaged_openordertempdata_averaging_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingconfigurations',
            name='external_url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
