# Generated by Django 4.2.14 on 2024-10-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_app', '0002_tradingconfigurations_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingconfigurations',
            name='external_url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
